In [9]:
class Employee:
    emp_num = 0
    
    def __init__(self, name, family_name, salary, department):
        self.name = name
        self.family_name = family_name
        self.salary = salary
        self.department = department
        Employee.emp_num += 1
        
    def average_salary(emp_sal):
        
        sum = 0
        for employee in emp_sal:
            sum += employee.salary
        return sum / Employee.emp_num
    
class FulltimeEmployee(Employee):
    def __init__(self,name,family_name,salary,department):
        super().__init__(name,family_name,salary,department)
    def full_time_benifits(self):
        print("Few benefits as full time employee")
        
        
def main():
    employees = []
    fte1 = FulltimeEmployee("shiny","sherly",50000,"software")
    fte1.full_time_benifits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("bhavya","maddineni",500000,"software")
    employees.append(fte2)
    e1 = FulltimeEmployee("snikitha","bommena",5000000,"IT")
    employees.append(e1)
    e2 = FulltimeEmployee("hari","priya",5000000,"IT")
    employees.append(e2)
    print("average_salary =", FulltimeEmployee.average_salary(employees))
    
if __name__ == "__main__":
    main()
    

Few benefits as full time employee
average_salary = 2637500.0


A class named Employee has been created. Data member emp_num is given. A constructor is created for all the given parameters. To get the average salary, a function is created. Fulltime employee class is created to inherit the properties of the employee class. average_salary funtion is created and employees list is passed as an argument to calculate average salary. Full_Time_Employee class has been created that extends the properties of Employee class. average_salary function is called by creating the object for Full_Time_Employee class.


In [13]:
import numpy as np
a = np.random.uniform(1,20,20)
print(a)

[ 5.63218298  3.99311861 12.8869148  15.21437301  8.64136367 19.03324548
 16.51013446 13.35243296  6.06179607 19.47416497  1.21632133  9.07604702
  4.66290426  5.70530911 16.99532946  6.89329849 17.13098599  7.39949922
 15.00066932 14.07822627]


In [14]:
# importing numpy
import numpy as np

# creating a numpy array
array = a;
# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array 4 x 5 : ")
print(reshaped)

Array : [ 5.63218298  3.99311861 12.8869148  15.21437301  8.64136367 19.03324548
 16.51013446 13.35243296  6.06179607 19.47416497  1.21632133  9.07604702
  4.66290426  5.70530911 16.99532946  6.89329849 17.13098599  7.39949922
 15.00066932 14.07822627]
First Reshaped Array 4 x 5 : 
[[ 5.63218298  3.99311861 12.8869148  15.21437301  8.64136367]
 [19.03324548 16.51013446 13.35243296  6.06179607 19.47416497]
 [ 1.21632133  9.07604702  4.66290426  5.70530911 16.99532946]
 [ 6.89329849 17.13098599  7.39949922 15.00066932 14.07822627]]


In [15]:
a = reshaped
b = a
b[np.arange(len(a)), a.argmax(1)] = 0
print(b)

[[ 5.63218298  3.99311861 12.8869148   0.          8.64136367]
 [19.03324548 16.51013446 13.35243296  6.06179607  0.        ]
 [ 1.21632133  9.07604702  4.66290426  5.70530911  0.        ]
 [ 6.89329849  0.          7.39949922 15.00066932 14.07822627]]


Imported numpy library and A vector has been created with random values of size 20 with range between 1 to 20. Array is reshaped to size of rows and columns of 4 and 5 using reshape method. Maximum element of each row of array is replaced with zero.